version: '3'
services:
  mysql:
    image: asoo571314/mysql:1.3
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ubuntu
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command: ["mysqld", "--user=mysql", "--lower_case_table_names=1"]
