version: '3'
services:
  jupyter-tutorial:
    image: asoo571314/jupyter-notebook:1.0
    container_name: jupyter_notebook
    user: root
    environment:
      - GRANT_SUDO=yes
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - ../mission1//work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
  myaql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iii
    ports:
      - "3306:3306"

